SimpleCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path ,include
from leads.views import landing_Page,LandingPageView,SignupView
from django.contrib.auth.views import (
                                        LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view() ,name = "landing_Page"),
    path('leads/',include('leads.urls',namespace ='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/',LoginView.as_view(),name='login'),
    path('reset_password/', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('signup/', SignupView.as_view(),name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from  .views import (LeadListView,LeadDetailView,LeadUpdateView,LeadCreateView,
                     LeadDeleteView,AssignAgentView,CategoryListView,CategoryDetailView,LeadCategoryUpdateView
                     )

app_name = 'leads'

urlpatterns =[
    path('',LeadListView.as_view(),name='lead_list'),
    path('<int:pk>/',LeadDetailView.as_view(),name='lead_detail'),
    path('<int:pk>/update',LeadUpdateView.as_view(),name='lead_update'),
    path('<int:pk>/assign_agent', AssignAgentView.as_view(), name='assign_agent'),
    path('<int:pk>/delete', LeadDeleteView.as_view(),name='lead_delete'),
    path('create/',LeadCreateView.as_view(),name='lead_create'),
    path('categories/',CategoryListView.as_view(),name='category_list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:pk>/category', LeadCategoryUpdateView.as_view(), name='lead_category_update'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_Agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Agent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class Lead(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent",null=True,blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",related_name="leads",on_delete=models.SET_NULL,null=True, blank=True)
    description = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number =models.CharField(max_length=20)
    email = models.EmailField()



    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Category(models.Model):
    # { Contacted,New,Converted,Unconverted }
    name = models.CharField(max_length=100)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

def post_user_created_signal(sender , instance, created,**kwargs):
    if created:
        UserProfile.objects.create(user = instance)



post_save.connect(post_user_created_signal , sender = User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.http import request
from .models import Lead, User, Agent, Category
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
            "email",
            "phone_number",
            'description'
        )


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        fields_classes = {"username": UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "category",
        )

leads/views.py
# pylint: disable=missing-module-docstring
from django.db.models.query import QuerySet
from django.core.mail import send_mail
from django.shortcuts import render ,redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, request
from django.views import generic
from .models import Category, Lead , Agent ,User
from .forms import  LeadForm , LeadModelForm ,CustomUserCreationForm ,AssignAgentForm ,LeadCategoryUpdateForm
from agents.mixins import OrganizerAndLoginRequiredMixin




# Create your views here.

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name ="landing.html"

def landing_Page(request):
    return render(request,'landing.html')


class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user

        #initial queryset  of lead list for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization =user.userprofile,agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization =user.agent.organization,agent__isnull=False)
            #filter for the agent that is logged in
            queryset =queryset.filter(agent__user = user)

        return queryset

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organizer:
            queryset = Lead.objects.filter(organization =user.userprofile,agent__isnull=True)
            context.update({
                "unassigned_leads" : queryset
            })
        return context

def lead_list(request):
    leads = Lead.objects.all()
    context = {
        'leads': leads
    }
    return render(request, 'leads/lead_list.html', context)


class LeadDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'

    def get_queryset(self):
        user = self.request.user
        #initial queryset  of lead list for the entire organization

        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
            #filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        'lead': lead
    }
    return render(request, 'leads/lead_detail.html', context)


class LeadCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = 'leads/lead_create.html'
    form_class =LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        """
        Send an Email when Lead Creates
        """
        lead = form.save(commit=False)
        lead.organization =self.request.user.userprofile
        lead.save()
        # Send Email
        send_mail(
            subject = "A New Lead has been created",
            message = "Please check the website for new lead",
            from_email = "test@test.com",
            recipient_list = ['test2@test.com']
        )
        return super(LeadCreateView, self).form_valid(form)


def lead_create(request):
    form = LeadModelForm()
    if request.method == 'POST':
        print("Receiving data")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            agent = form.cleaned_data['agent']
            form.save()
            return redirect('/leads')
    context = {
        'form': form
    }
    return render(request, 'leads/lead_create.html', context)


class LeadUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm

    def get_queryset(self):
        user = self.request.user
        #initial queryset  of lead list for the entire organization
        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse("leads:lead_list")


def lead_update(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance = lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context ={
        'form' : form ,
        'lead' : lead
    }
    return render(request, 'leads/lead_update.html',context)


class LeadDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/lead_delete.html'

    def get_queryset(self):
        user = self.request.user
        #initial queryset  of lead list for the entire organization
        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse("leads:lead_list")

def lead_delete(request,pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')



class AssignAgentView(OrganizerAndLoginRequiredMixin,generic.FormView):
    template_name ="leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self,**kwargs):
        kwargs = super(AssignAgentView,self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead =Lead.objects.get(id=self.kwargs['pk'])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView,self).form_valid(form)


class CategoryListView(LoginRequiredMixin,generic.ListView):
    template_name = 'leads/category_list.html'
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(CategoryListView, self).get_context_data(**kwargs)

        #initial queryset  of lead list for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization =user.userprofile)
        else:
            queryset = Lead.objects.filter(organization = user.agent.organization)
        context.update({
            "unassigned_leads_count" : queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user = self.request.user

        #initial queryset  of lead list for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization =user.agent.organization)
            #filter for the agent that is logged in
        return queryset

class CategoryDetailView(LoginRequiredMixin,generic.DetailView):
    template_name ="leads/category_detail.html"
    context_object_name = "category"



    def get_queryset(self):
        user = self.request.user

        #initial queryset  of lead list for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization)
            #filter for the agent that is logged in
        return queryset

class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):
    template_name = 'leads/lead_category_update.html'
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
            #filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead_detail", kwargs={"pk" :self.get_object().id})

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto mb-5 ">
    <div>
        <a class="hover:text-blue-500 mt-5" href=" {% url 'leads:lead_list'%}">Go Back To leads</a>
    </div>
    <div class="text-4xl mb-5 ">
        <h1>Assign lead to an agents</h1>
    </div>
    <form method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full bg-blue-500 text-white hover:bg-blue-600 px-1 py-2 rounded-md"> submit
        </button>
    </form>
</div>
{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
                {{ category.name }}
            </h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                these are the leads of category: {{ category.name }}
            </p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            first_name
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            last_name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for lead in category.leads.all %}
                    <tr>
                        <td class="px-4 py-3">
                            <a class="hover:text-blue-500" href="{% url 'leads:lead_detail' lead.pk %}">
                                {{ lead.first_name }}
                            </a>
                        </td>
                        <td class="px-4 py-3">{{lead.last_name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                Categories are related to the leads
            </p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Count</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3"> UnAssigned</td>
                        <td class="px-4 py-3">{{ unassigned_leads_count }}</td>
                    </tr>
                    {% for category in category_list %}
                    <tr>
                        <td class="px-4 py-3">
                            <a href=" {% url 'leads:category_detail' category.pk %} ">{{ category.name }}
                        </td> </a>
                        <td class="px-4 py-3">TO DO Count</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead Details</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead_detail' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        OverView
                    </a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Category
                    </a>
                    <a href="{% url 'leads:lead_update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update
                    </a>
                </div>
                <form method='post'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit'
                        class="mb-5  w-full bg-blue-500 text-white hover:bg-blue-600 px-1 py-2 rounded-md">
                        submit
                    </button>
                </form>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
    </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="hover:text-blue-500" href=>
        <a href=" {% url 'leads:lead_list'%}">Go Back To leads</a>
    </div>
    <div>
        <h1 class="text-4xl">
            Create a new Lead
        </h1>
    </div>
    <div>
        <form method='post' class='mt-5'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full bg-blue-500 text-white hover:bg-blue-600 px-1 py-2 rounded-md">
                submit
            </button>
        </form>
    </div>
</div>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <a  class="hover:text-blue-500" href=" {% url 'leads:lead_list'%}">Go Back To leads</a>
    <h1 class="text-4xl mb-5 ">Do you Want to delete the Lead?</h1>
    <form method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full bg-blue-500 text-white hover:bg-blue-600 px-1 py-2 rounded-md">
            submit
        </button>
    </form>
</div>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead Details</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">OverView</a>
          <a href="{% url 'leads:lead_category_update' lead.pk%}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead_update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Lead</a>
        </div>
        <p class="leading-relaxed mb-4">
          You will receive description of lead if there are any.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Agent</span>
          <span class="ml-auto text-gray-900">{{lead.agent}}</span>
        </div>
      <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">N/A</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">cell phone</span>
          <span class="ml-auto text-gray-900">{{lead.phone_number}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">email</span>
          <span class="ml-auto text-gray-900">{{lead.email}}</span>
        </div>
        <div class="flex">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
            viewBox="0 0 24 24">
          </svg>
          </button>
        </div>
      </div>
      <img alt="test" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b  border-gray-200">
      <div>
        <h1 class='text-4xl text-gray-800'>
          Leads
        </h1>
        <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category_list' %}">
          View the Categories
        </a>
        {% if request.user.is_organizer %}
      </div>
      <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead_create' %}">
        Create a Lead
      </a>
    </div>
    {% endif %}
    <div class="flex flex-wrap -m-4">
      {% for lead in leads%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              {{lead.description}}
            </p>
            <a href="{% url 'leads:lead_detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
              View Details
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="w-full">
        <h1 class='text-4xl text-gray-800 p-4'>
          Unassigned Leads
        </h1>
      </div>
      {% if unassigned_leads.exists %}
      {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              {{lead.description}}
            </p>
            <a href="{% url 'leads:assign_agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
              Assign to an Agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      {%endif %}
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead Details</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Update
          </a>
          <a href="{% url 'leads:lead_category_update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            Category
          </a>
          <a href="{% url 'leads:lead_detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
            OverView
          </a>
        </div>
        <form method='post'>
          {% csrf_token %}
          {{ form|crispy }}
          <button type='submit' class=" mb-5 w-full bg-blue-500 text-white hover:bg-blue-600 px-1 py-2 rounded-md">
            submit</button>
        </form>
        <a  href="{% url 'leads:lead_delete' lead.pk  %}"class=" mgt-5 w-1/2  text-white justify-center bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
          Delete
        </a>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400">
    </div>
  </div>
  </div>
</section>
{% endblock content %}